### ISSUE TITLE
[Feature request] ARM Support

### ISSUE THREAD

**Issue by iMonZ** [kz6fittycent/mc-installer#10]
Since Java support Arm out of the box it shouldn't be hard right?

**Comment by hulloanson** [comment]
This installer downloads the official minecraft launcher. That launcher is for `X86_64`. To launch minecraft in arm would be a launcher project.

**Comment by kz6fittycent** [comment]
@iMonZ @hulloanson is correct. I had asked this question in a snap creators' group and the same answer was presented. I'm afraid we're at the mercy of Mojang/MS at this point. 

There may be a way to create something that just launches MC that uses `bash`, wrap it in a GUI and there you have it, but I'm afraid I'm a bit taxed for time at present. Not sure if you're aware that the launcher is actually "[broken](https://github.com/kz6fittycent/mc-installer/issues/9 )" right now and basically no one's using the snap to play MC - Mojang is to blame for this one.
