### ISSUE TITLE
Older versions (like 1.12.2) requires the xrandr binary

### ISSUE THREAD

**Issue by nsg** [kz6fittycent/mc-installer#23]
I was unable to run Minecraft 1.12.2, it throws the following error:

```
java.lang.ExceptionInInitializerError
	at bib.av(SourceFile:661)
	at bib.aq(SourceFile:456)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more
```

## Expected behavior

Minecraft 1.12.2 starts

## Observed behavior

An Exception it thrown, my understanding is that older versions of lwjgl parses the output of the xrandr binary, this is not part of core20, or the staged packages so that fails. The fix is to stage `x11-xserver-utils`, [I'm able to play with this fix](https://github.com/nsg/snap-minecraft/commit/a20394deb9dc8fd68e8b5619e5fcd90ed65c7b3d).

Suggested solutions:

1) Document that older versions that X is not supported, or
2) Include `x11-xserver-utils` (or just xrandr) in the snap

## OS Info

Ubuntu 20.04.2 LTS

## Snap version (`snap info mc-installer`)

567

## Snapd version (run `snap --version`) 

snap    2.51.1
snapd   2.51.1
series  16
ubuntu  20.04
kernel  5.4.0-80-generic

## Logs can be pasted here - 

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 7/26/21 4:19 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bib.av(SourceFile:661)
	at bib.aq(SourceFile:456)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bib.av(SourceFile:661)
	at bib.aq(SourceFile:456)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-80-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329831424 bytes (314 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by kz6fittycent** [comment]
Okay, let me do a quick test build and get back to you. Thanks for posting this.

**Comment by kz6fittycent** [comment]
Local build works for latest version. I've pushed the changes to `master` and will be building the latest snap in the `--edge` channel. I'll ask that you test that to ensure it's working as intended. 

The build should be done in about an hour (max).

**Comment by kz6fittycent** [comment]
@nsg any feedback? Did the latest version in `edge` work for you?

**Comment by nsg** [comment]
I haven't had time to actually play the game yet, but it looks good. 1.12.2 launches without any stacktraces so it looks good. I will try to give it a real test in a hour or so.

**Comment by nsg** [comment]
It works! Nice, thank you for a fast fix!

**Comment by kz6fittycent** [comment]
Alright! Thanks for your help and I'll get this pushed to `stable`.
