### ISSUE TITLE
ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper'

### ISSUE THREAD

**Issue by Darkproduct** [kz6fittycent/mc-installer#26]
First of all I'm not really sure if this is a problem, but I stuck there trying to fix this for some hours before I found out, that my problem had nothing to do with this and I'm an idiot. My problem here is, that there is an error in the logs that to my knowledge doesn't affect anything. So this post can either be closed, but then at least other will know that they are searching in the wrong place, or this does indeed affect something and needs to be fixed.

I found a related post here: https://www.minecraftforum.net/forums/support/java-edition-support/2828845-a-little-warning-when-startup
But installing `flite` didn't fix anything, probably because this is a snap.

### Expected behavior -
No errors in the logs

### Observed behavior - 
```
[Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':
libflite.so.1: cannot open shared object file: No such file or directory
libflite.so.1: cannot open shared object file: No such file or directory
```
### OS Info
Ubuntu 20.04 LTS with Xfce and ZSH

### Snap version (`snap info mc-installer`) - 
```
❯ snap info mc-installer
name:      mc-installer
summary:   A simple installer for Minecraft - Java Edition
publisher: James Tigert (kz6fittycent)
store-url: https://snapcraft.io/mc-installer
contact:   https://github.com/kz6fittycent/mc-installer
license:   MIT
description: |
  **A SPECIAL NOTE ABOUT LOG4J**
  
  `mc-installer` will always attempt to download the latest version of Minecraft. Version `1.18.1`
  is considered secure.
  
  Go here to learn more:
  https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition?ref
  =launcher
  
  
  A simple installer for Minecraft - Java Edition.
commands:
  - mc-installer
snap-id:      VcdcPCY35DfyUSApgyijx9oes01cIFKX
tracking:     latest/stable
refresh-date: today at 14:51 CET
channels:
  latest/stable:    10.2 2021-12-20 (574) 103MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      10.2 2021-12-17 (574) 103MB -
installed:          10.2            (574) 103MB -
```

###  Snapd version (run `snap --version`) 
```
❯ snap --version
snap    2.53.4
snapd   2.53.4
series  16
ubuntu  20.04
kernel  5.11.0-27-generic
```

**Comment by kz6fittycent** [comment]
Okay, looks like it was just a library I needed to add. I've created a new version `10.3` in the `edge` channel. Do you mind testing it on your end?

`sudo snap refresh mc-installer --edge`

**Comment by Darkproduct** [comment]
Looks good. There error is gone. 

But @kz6fittycent one last question. I updated and I now have two `.minecraft` directories, one in `574`  and one in `575` and both of them have the same data. But only the newer one is used. Can I just delete the old one? The folder is rather big and I think its strange to have more then one.

**Comment by kz6fittycent** [comment]
Sure you can delete that.
