### ISSUE TITLE
Cannot set the installation directory on a non-system hard drive.

### ISSUE THREAD

**Issue by ghost** [kz6fittycent/mc-installer#28]
* Expected behavior - I can install the game on a non-system hard drive.

* Observed behavior - When attempting to set the installation directory on a non-system hard drive, an error appears:
**Error opening directory 'media/user/<hard drive>': Permission denied**
![image](https://user-images.githubusercontent.com/79970290/214926735-d0b0e884-d090-415f-ae98-b8075600ead7.png)

* OS Info - Kubuntu 22.10

* Snap version- 10.3

* Snapd version - 2.58

Attempting to fix the issue with `sudo snap connect mc-installer:removable-media` results in the following error:
        _snap "mc-installer" has no plug named "removable-media"_

**Comment by kz6fittycent** [comment]
Commit https://github.com/kz6fittycent/mc-installer/commit/423d2cb25676093652e3061dc6bb0e195901aec0 

Will need you to test by refreshing to `--edge` once the build completes. It will take about an hour from now.

**Comment by kz6fittycent** [comment]
eh...this one: https://github.com/kz6fittycent/mc-installer/commit/6cedad1fcdc45dc68504a39359f9f3697bf7f35e

**Comment by ghost** [comment]
> eh...this one: [6cedad1](https://github.com/kz6fittycent/mc-installer/commit/6cedad1fcdc45dc68504a39359f9f3697bf7f35e)

I have no idea how to build this, I tried using make, but it says that there is no makefile.

**Comment by kz6fittycent** [comment]
No, I apologize. All you need to do is refresh the snap to the edge channel. Use the following command: 'sudo snap refresh mc-installer --edge'

**Comment by ghost** [comment]
Yep, that worked. Thank you for the help!
