### ISSUE TITLE
Pass MESA_GL_VERSION_OVERRIDE to actual Minecraft invocation?

### ISSUE THREAD

**Issue by sndrsmnk** [kz6fittycent/mc-installer#31]
# Please follow the general troubleshooting steps first:

- [x] Try running `snap run mc-installer`
- [x] Refreshing the snap to ensure you have the latest `stable` version
- [x] Restart `snapd`

Upgraded my machine to Ubuntu 24.04 'Noble', Minecraft fails to start stating `GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig`

Aparently my OpenGL is too new now. :1st_place_medal: 

I can make it work by exporting `MESA_GL_VERSION_OVERRIDE=4.3` before running the MC jar, but going through `snap run mc-installer` this env var seems to get lost somewhere. It is there when i run `snap run --shell mc-installer` and look at the env, but somewhere before the actual java invocation it gets cleared?

* OS Info -
```
$ glxinfo | grep -e "OpenGL version" -e "Core" -e "Compatible"
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.0-2ubuntu3
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.0-2ubuntu3

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Noble Numbat (development branch)
Release:	24.04
Codename:	noble
```

* Snap version (`snap info mc-installer`) - 
```
tracking:     latest/stable
refresh-date: 12 days ago, at 22:01 CET
channels:
  latest/stable:    12.3 2023-12-08 (619) 117MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      12.3 2023-12-08 (619) 117MB -
installed:          12.3            (619) 117MB -
```

* Snapd version (run `snap --version`) 
```
snap --version        
snap    2.60.4+23.10.1
snapd   2.60.4+23.10.1
series  16
ubuntu  24.04
kernel  6.6.7-060607-generic
```

* Logs can be pasted here - 
```
Failed to create window: net.minecraft.class_1041$class_4716: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
```

**Comment by kz6fittycent** [comment]
I added a new flag to the snap's yaml. Let's see if this does the trick. 

If you don't mind, please refresh to the `edge` channel in about an hour or so, and let me know. My GPU is old...so...I can't duplicate.

**Comment by kz6fittycent** [comment]
Sorry - the build didn't go thru - I've just triggered it manually. Perhaps another hour.

**Comment by kz6fittycent** [comment]
`edge` version is up and ready. Again, I can't test whether the new setting works for you or not, but it's running here on my machine (all AMD).

**Comment by sndrsmnk** [comment]
Oh thanks for the quick commits!  Just tried 13.0 from edge channel.  Same issue though. :/
I also run on AMD.

I did notice the official minecraft-launcher works fine. Even without exporting that MESA_GL_VERSION_OVERRIDE env var first. So now i wonder if this var is needed at all and the issue seems to be somewhere else.

Not sure how to proceed debugging this though.

**Comment by kz6fittycent** [comment]
Nor am I. We can leave this issue open if you like, but I'll have to rely on you for debugging and suggestions. If you do figure it out, feel free to fork the repo and provide a PR for a fix.

**Comment by sndrsmnk** [comment]
I'll close this for now then. I hope others can find it then might they experience the same thing. Perhaps during the festive days i'll find time to play around with this a bit. Could well be that some other snap-part needs updating. Thanks so far!
