### ISSUE TITLE
Minecraft does not use my Intel 750 GPU

### ISSUE THREAD

**Issue by AnnualPath** [kz6fittycent/mc-installer#33]
Hello,

For some reason Minecraft is using my integrated Intel graphics and not my Intel GPU. Do you know a fix for this issue?

![Screenshot from 2024-04-20 07-33-47](https://github.com/kz6fittycent/mc-installer/assets/135929822/61f7be65-cccc-494e-9533-7722ad8140c9)

**Comment by kz6fittycent** [comment]
I have searched for several solutions online and I'm not able to identify the best path forward. Unfortunately, I can't duplicate this issue for you.

**Comment by AnnualPath** [comment]
Thank you for looking for a solution. Do you think installing the .deb Minecraft file might be a solution or is the the same as the file found on Minecraft's website?

**Comment by kz6fittycent** [comment]
I am not certain. This snap uses the java-based app, and the snap is just a vehicle to set that up for the user.
