### ISSUE TITLE
Can't run 1.12.2 or below, Exit Code 0

### ISSUE THREAD

**Issue by ghost** [kz6fittycent/mc-installer#8]
# Please follow the general troubleshooting steps first:

- [Y ] Try running `snap run mc-installer`
- [Y ] Refreshing the snap to ensure you have the latest `stable` version
- [Y ] Restart `snapd`

* Expected behavior -

Launches 1.12.2 without issues

* Observed behavior - 

Instantly crashes with exit code 0 and empty log file

* OS Info -

POP OS 20.10
openjdk version "1.8.0_275"

* Snap version (`snap info mc-installer`) - 
name:      mc-installer
summary:   A simple installer for Minecraft - Java Edition
publisher: James Tigert (kz6fittycent)
store-url: https://snapcraft.io/mc-installer
contact:   merlijn.sebrechts@gmail.com
license:   MIT
description: |
  A simple installer for Minecraft - Java Edition.
  
  The original version of Minecraft! Java Edition has cross-platform play
  between Windows, Linux and macOS, and also supports user-created skins and
  mods. Includes a decade’s worth of updates, with much more to come!
  
  * Supports user-created skins and mods
  * Compatible with Realms for Java Edition
  * Access to snapshots, which enable early access to new features
  * Receives frequent updates via the game launcher
  * Free trial version available
commands:
  - mc-installer
snap-id:      VcdcPCY35DfyUSApgyijx9oes01cIFKX
tracking:     latest/stable
refresh-date: today at 16:26 GMT
channels:
  latest/stable:    7.2 2020-12-11 (520) 41MB -
  latest/candidate: ↑                         
  latest/beta:      ↑                         
  latest/edge:      7.2 2020-11-29 (520) 41MB -
installed:          7.2            (520) 41MB -

* Snapd version (run `snap --version`) 
snap    2.48.1
snapd   2.48.1
series  16
pop     20.10
kernel  5.8.0-7630-generic

* Logs can be pasted here - 
n/a

I've tried everything. I installed java 8 with "sudo apt install openjdk-8-jre-headless"
and selected it with "sudo update-alternatives --config java". Can't change java executable path to anything as it always thinks it's non existant.

**Comment by kz6fittycent** [comment]
Hi and thanks for opening this issue, 

The system's (native) version of Java won't matter as the snap is packaged with the supported version of it (version 8). Debug logs are contained in `~/snap/mc-installer/current/minecraft-launcher/debug.log`


Unfortunately, the issue you're having has nothing to do with the snap, it's the Minecraft launcher - it's incompatible, per the warning when attempting to run an older (unsupported) version. See screenshot.

![Screenshot from 2020-12-19 11-56-41](https://user-images.githubusercontent.com/14829816/102696119-92c15680-41f1-11eb-9498-396b2f3860ac.png)

You might be able to run it natively using the terminal and your locally installed version of java.

Sorry I can't help with this.
