### ISSUE TITLE
MC-Installer fails to launch

### ISSUE THREAD

**Issue by kz6fittycent** [kz6fittycent/mc-installer#9]
# Please follow the general troubleshooting steps first:

- [ x] Try running `snap run mc-installer`
- [ x] Refreshing the snap to ensure you have the latest `stable` version
- [ x] Restart `snapd`

* Expected behavior -
MC-installer should launch when clicking icon

* Observed behavior - 
Fails to load.

`snap run mc-installer` renders:

```
...
[Warning: 2021-03-02 20:17:43.555355464: PistonUpdate.cpp(530)] Manifest merge contains duplicate entry for folder: /.../minecraft-launcher
[Info: 2021-03-02 20:17:43.555764806: PistonUpdate.cpp(632)] Target path: .../.minecraft/launcher
Failed to iterate over the /home/$USER/.minecraft/launcher directory: Permission denied
[Error: 2021-03-02 20:17:43.556253078: PistonUpdate.cpp(643)] Inspection of .../.minecraft/launcher failed. Error: Permission denied
...
```

* OS Info -
Pop!_OS 20.04

* Snap version (`snap info mc-installer`) - 
`8.0`

* Snapd version (run `snap --version`) 
```
snap    2.48.3+20.04
```

* Logs can be pasted here - 

See above.

---

### Consider contributing to this project with a PR ###

https://github.com/kz6fittycent/mc-installer/pulls

**Comment by edmcdonagh** [comment]
Just to let you know @kz6fittycent we have seen this on Ubuntu too (and a rather upset nine-year old as a result!)

I hope you can find what is going wrong!

**Comment by kz6fittycent** [comment]
More logs:
https://hatebin.com/yrrlntbzeo

**Comment by kz6fittycent** [comment]
> Just to let you know @kz6fittycent we have seen this on Ubuntu too (and a rather upset nine-year old as a result!)
> 
> I hope you can find what is going wrong!

Yeah it's pretty irritating - I released a new rev after testing in the `edge` channel, worked for like 2-3 days, then this starts happening. What I'm worried about is that the minecraft binary is actually trying to force the path to `/home/$USER/` instead of being more agnostic. 

If that's the case, I may not be able to fix this. 

That said, if your 9-yo still wants to play, the binary can be launched manually via `~/snap/mc-installer/current/./minecraft-launcher`

I know that's janky but hey, sometimes you gotta play some MC.

**Comment by edmcdonagh** [comment]
Thanks - he's back in, though his single player worlds and skins aren't appearing. I don't know if that would be related to how we launched it, or if there is something else going on! 

Either way, I hope you can find what is going on and fix it. And thanks for reaching out to help him back in to MC!

Would Ubuntu logs be of any additional help?

**Comment by kz6fittycent** [comment]
> Thanks - he's back in, though his single player worlds and skins aren't appearing. I don't know if that would be related to how we launched it, or if there is something else going on!
> 
> Either way, I hope you can find what is going on and fix it. And thanks for reaching out to help him back in to MC!
> 
> Would Ubuntu logs be of any additional help?

I don't think so. This is something that minecraft is doing - and I don't know why yet.

**Comment by merlijn-sebrechts** [comment]
For some reason, the new launcher gets the `home` directory from `/etc/passwd` instead of using the `$HOME` variable. We can modify this behavior with the `workDir` flag.

```
$SNAP_USER_DATA/minecraft-launcher/./minecraft-launcher --workDir $SNAP_USER_DATA/.minecraft
```

For more information about all the flags supported by `minecraft-launcher`, see https://minecraft.gamepedia.com/Minecraft_Launcher

When running it like this, I get a bit further. At some point, however, the Minecraft launcher restarts itself and "forgets" the `workDir` parameter, bouncing against the exact same issue.

**Comment by merlijn-sebrechts** [comment]
* I created an issue for the `workDir` parameter not working: https://bugs.mojang.com/browse/MCL-17153
* I created an issue for Minecraft not respecting the $HOME variable: https://bugs.mojang.com/browse/MCL-17155

**Comment by kz6fittycent** [comment]
Thanks @galgalesh I was able to get a little further and still crashed. @edmcdonagh if you'd like to verify it's still not working, please refresh the snap to the `--edge` channel with the command: `sudo snap refresh --edge mc-installer`

**Comment by merlijn-sebrechts** [comment]
I created a request for access to the `$HOME/.minecraft` directory. This is useful regardless of whether we find a fix for this issue or not. If we are granted access, that _might_ fix our issue too, because then we can simply use the directory Minecraft is trying to use.

https://forum.snapcraft.io/t/auto-connect-personal-files-request-for-mc-installer/23096

**Comment by edmcdonagh** [comment]
Thanks @kz6fittycent @galgalesh - as you describe it gets further, downloads whatever it downloads, then 
```
[Info: 2021-03-03 22:36:04.667890973: ProductManager.cpp(212)] Product library dir set to /home/george/snap/mc-installer/539/.minecraft/products
[Info: 2021-03-03 22:36:04.667972749: Xal.lib(0)] XAL: Generate random bytes platform callback reported completion status 'XalPlatformOperationResult_Success' (0)
[Info: 2021-03-03 22:36:04.667998502: AccountData.cpp(317)] Migrating user accounts from profiles file...
[Info: 2021-03-03 22:36:04.668068594: SkinManager.cpp(251)] Failed to read skins file: .../.minecraft/launcher_skins.json ErrNo such file or directory
[Info: 2021-03-03 22:36:04.668463897: CefUI.cpp(145)] Web cache path: /home/george/snap/mc-installer/539/.minecraft/webcache2
[Info: 2021-03-03 22:36:04.689997157: NetQueue.cpp(154)] NetQueue: Setting up.
[Info: 2021-03-03 22:36:04.690199363: mainLinux.cpp(160)] Running launcher bootstrap (version 887)
[Error: 2021-03-03 22:36:04.710146927: Settings.cpp(40)] Failed to open configuration file: Permission denied
[Error: 2021-03-03 22:36:04.711072327: LauncherPluginLinux.cpp(20)] Failed to load /home/george/.minecraft/launcher/liblauncher.so: /home/george/.minecraft/launcher/liblauncher.so: cannot open shared object file: Permission denied
[Error: 2021-03-03 22:36:04.711182751: mainLinux.cpp(199)] Couldn't open //.../liblauncher.so on child subprocess
[Info: 2021-03-03 22:36:04.689997027: NetQueue.cpp(154)] NetQueue: Setting up.
[Info: 2021-03-03 22:36:04.690199271: mainLinux.cpp(160)] Running launcher bootstrap (version 887)
[Error: 2021-03-03 22:36:04.713427696: Settings.cpp(40)] Failed to open configuration file: Permission denied
[Error: 2021-03-03 22:36:04.714509777: LauncherPluginLinux.cpp(20)] Failed to load /home/george/.minecraft/launcher/liblauncher.so: /home/george/.minecraft/launcher/liblauncher.so: cannot open shared object file: Permission denied
[Error: 2021-03-03 22:36:04.714882978: mainLinux.cpp(199)] Couldn't open //.../liblauncher.so on child subprocess
```
Then the GPU process crashes a few times (!!! but then, it is an old EliteBook...), and
```
[0303/223605.113569:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 8 time(s)
Created browser window for reuse: 0x2600001
[Info: 2021-03-03 22:36:05.126947331: browser_window_std_gtk.cpp(105)] my_gtk_realize: 0x1f6e700
[Info: 2021-03-03 22:36:05.141106724: root_window_gtk.cpp(322)] Window icon fixed successfully (AB#474691).
[Info: 2021-03-03 22:36:05.141188481: root_window_manager.cpp(79)] Main window has been opened: 0x20b7f90
[0303/223605.154544:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 9 time(s)
[0303/223605.154758:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[Info: 2021-03-03 22:36:05.124845806: NetQueue.cpp(154)] NetQueue: Setting up.
[Info: 2021-03-03 22:36:05.125050875: mainLinux.cpp(160)] Running launcher bootstrap (version 887)
[Error: 2021-03-03 22:36:05.168205938: Settings.cpp(40)] Failed to open configuration file: Permission denied
[Error: 2021-03-03 22:36:05.169431155: LauncherPluginLinux.cpp(20)] Failed to load /home/george/.minecraft/launcher/liblauncher.so: /home/george/.minecraft/launcher/liblauncher.so: cannot open shared object file: Permission denied
[Error: 2021-03-03 22:36:05.169596946: mainLinux.cpp(199)] Couldn't open //.../liblauncher.so on child subprocess
/snap/mc-installer/539/launch: line 19: 65605 Trace/breakpoint trap   (core dumped) ( $SNAP_USER_DATA/minecraft-launcher/./minecraft-launcher --workDir $SNAP_USER_DATA/.minecraft )
```

**Comment by kz6fittycent** [comment]
Yeah I'm getting the same errors you are @edmcdonagh - so we still have some waiting to do. I'm hoping that the auto-connect request that @galgalesh submitted gets approved and we can get it to work again, regardless of what mojang does.

True story: I don't even play minecraft, I started working on this snap so my kids could...

**Comment by merlijn-sebrechts** [comment]
As a temporary solution, we could publish a version of the snap which is hardcoded to download a previous version of the launcher that doesn't have the issue here. I'll take a look at this tomorrow.

**Comment by kz6fittycent** [comment]
I had thought of that but I'm not sure how well it'll be received. There may be some users who want to use the latest- that said, at this point, I guess that's fine. I can take a look at the link I use to grab the files and hard code it.

**Comment by kz6fittycent** [comment]
> As a temporary solution, we could publish a version of the snap which is hardcoded to download a previous version of the launcher that doesn't have the issue here. I'll take a look at this tomorrow.

I'm having a hard time finding WHERE to get the older version - I thought maybe I could use some code from the `mc-server-installer` snap but that's for the actual `.jar`, not the `minecraft-launcher`.

**Comment by kz6fittycent** [comment]
@galgalesh I see your issues with MC aren't getting any traction, nor is the request to add the personal-files plug. 

I'm still not having any luck finding the actual older `minecraft-launcher` binary. Getting an older `.jar` is easy. Should we just go that direction? Just edit the `launch` script to load the `.jar` file?

**Comment by hulloanson** [comment]
It's a pity snap doesn't support mapping home through `layout`. Now I'm making do with docker LOL.

**Comment by merlijn-sebrechts** [comment]
I found an older version of the launcher on my other computer. I uploaded it to archive.org. Can you test this one: https://archive.org/download/minecraft-launcher_202103/Minecraft.tar.gz

Simply changing the URL in `download-launcher.py` should do the trick.

**Comment by kz6fittycent** [comment]
Building locally now. Stand by.

**Comment by kz6fittycent** [comment]
My local build and testing was successful. PR'd to master. New version being built in `--edge` now. Be prepared to test @galgalesh, @hulloanson  and @edmcdonagh (if you can). TYVM.

**Comment by kz6fittycent** [comment]
`--edge` is working great - version 8.1. 

If you're able to test, and get positive results (very likely), I'll push to `--stable`. If I don't hear anything before I retire tonight, I'll assume all is well and push anyway, as I'm sure that @edmcdonagh has a 9-yo who's jonesing for some MC. :P

**Comment by Grimpen** [comment]
Looking forward to a fix, even if temporary.  I've got a 9 yo & 6 yo looking to punch wood.

I appreciate your efforts!

**Comment by hulloanson** [comment]
It works, though it downloads the launcher every time. do a check?

**Comment by merlijn-sebrechts** [comment]
Note: Mojang fixed the issue from their side and will release a new version of the launcher soon: https://bugs.mojang.com/browse/MCL-17155

In the meantime, we're stuck on the older version.

> It works, though it downloads the launcher every time. do a check?

The code currently does a check, but archive.org doesn't supply the HTTP headers we need to do a proper check so the code fallsback to downloading the new installer every time. I'll take a look if we can't have a smarter fallback mechanism.

**Comment by kz6fittycent** [comment]
In the meantime we've got a working build and we'll keep this going until Mojang comes through. @galgalesh I wonder if we could build in a quick backup of the previous launcher before downloading the latest?

**Comment by merlijn-sebrechts** [comment]
>  @galgalesh I wonder if we could build in a quick backup of the previous launcher before downloading the latest?

That would've been useful for previous versions, but the latest version of the launcher updates itself on startup, so even if we wanted to, we won't be able to use a previous version of the launcher. The one on archive.org is one of the last launchers to not auto-update.

**Comment by merlijn-sebrechts** [comment]
With this PR, mc-installer should only download the launcher once: https://github.com/kz6fittycent/mc-installer/pull/12

**Comment by kz6fittycent** [comment]
Looks like a `beta` has been released for the new launcher: https://bugs.mojang.com/browse/MCL-17155

**Comment by kz6fittycent** [comment]
I tried grabbing what I thought might be the latest `minecraft-launcher` and we're not out of the woods yet:

```
snap run mc-installer
Gtk-Message: 10:30:11.624: Failed to load module "appmenu-gtk-module"
Gtk-Message: 10:30:12.020: Failed to load module "canberra-gtk-module"
[Info: 2021-03-11 16:30:12.594502003: NetQueue.cpp(157)] NetQueue: Setting up.
[Info: 2021-03-11 16:30:12.594661482: NetQueue.cpp(575)] NetQueue: worker thread started.
[Info: 2021-03-11 16:30:12.594822313: mainLinux.cpp(250)] Running launcher bootstrap (version 915)
[Debug: 2021-03-11 16:30:12.595200592: PlatformLinux.cpp(44)] HOME dir (getpwuid): /home/james
[Debug: 2021-03-11 16:30:12.595211423: PlatformLinux.cpp(49)] HOME dir (env): /home/james/snap/mc-installer/x1
[Error: 2021-03-11 16:30:12.597991133: Settings.cpp(40)] Failed to determine configuration file size: No such file or directory
[Info: 2021-03-11 16:30:12.598405449: Common.cpp(32)] Native Launcher Version: 915
[Info: 2021-03-11 16:30:12.598422451: Common.cpp(33)] Operating System: Linux
[Info: 2021-03-11 16:30:12.598433812: Common.cpp(34)] Application Data directory: //.../.minecraft
[Info: 2021-03-11 16:30:12.598447037: Common.cpp(35)] Executable Path: /.../minecraft-launcher
[Info: 2021-03-11 16:30:12.598457196: Common.cpp(36)] App Directory dir: //.../minecraft-launcher
[Info: 2021-03-11 16:30:12.598467466: Common.cpp(37)] Game data directory: //.../.minecraft
[Info: 2021-03-11 16:30:12.598477444: Common.cpp(38)] Launcher dir: //.../launcher
[Info: 2021-03-11 16:30:12.598489837: Common.cpp(39)] Java dir: //.../jre-x64
[Info: 2021-03-11 16:30:12.598500017: Common.cpp(40)] TmpDir dir: //.../MinecraftLauncher.1000
[Info: 2021-03-11 16:30:12.598510025: Common.cpp(41)] x64: true
[Info: 2021-03-11 16:30:12.598671007: mainLinux.cpp(308)] relaunchedExe: /home/james/snap/mc-installer/x1/.minecraft/launcher/minecraft-launcher selfExe: /home/james/snap/mc-installer/x1/minecraft-launcher/minecraft-launcher
[Info: 2021-03-11 16:30:12.598682328: mainLinux.cpp(312)] Top level executable, forwarding signals.
[Error: 2021-03-11 16:30:12.598691305: mainLinux.cpp(330)] Invalid start directory!
MessageBox(Minecraft Launcher): Cannot start Minecraft in "/home/james/snap/mc-installer/x1/.minecraft": the specified path is not a valid directory.
```

Built locally from the `testing` branch.

**Comment by merlijn-sebrechts** [comment]
Seems like they broke it even further, it doesn't even work with the regular home directory anymore. Not what I expect from a company the size of Mojang, honestly.. I added another comment to the bug report.

**Comment by kz6fittycent** [comment]
Looks like others are reporting the same thing(s): https://bugs.mojang.com/browse/MCL-17263

Maybe it'll gain some more traction and they'll consider rolling back to the previous configuration...you know, since it worked??

**Comment by merlijn-sebrechts** [comment]
Though the new debug info shows they're using `getpwuid` to get the home directory. We could actually use an `LD_PRELOAD` to inject a patched version of `getpwuid` which refers to the snap home directory. But that requires a semi-working launcher ;)

https://forum.snapcraft.io/t/the-homeishome-launcher-fix-snapped-apps-that-wrongly-referring-to-the-users-real-home-directory-instead-of-home/19763

**Comment by kz6fittycent** [comment]
> Though the new debug info shows they're using `getpwuid` to get the home directory. We could actually use an `LD_PRELOAD` to inject a patched version of `getpwuid` which refers to the snap home directory. But that requires a semi-working launcher ;)
> 
> https://forum.snapcraft.io/t/the-homeishome-launcher-fix-snapped-apps-that-wrongly-referring-to-the-users-real-home-directory-instead-of-home/19763

Oh I like that idea....

**Comment by hulloanson** [comment]
omg...

**Comment by kz6fittycent** [comment]
> omg...

wat?

**Comment by hulloanson** [comment]
I was amazed how far one would go to work around to make snaps work... patching `getpwuid`? not something I have thought about

**Comment by kz6fittycent** [comment]
> Though the new debug info shows they're using `getpwuid` to get the home directory. We could actually use an `LD_PRELOAD` to inject a patched version of `getpwuid` which refers to the snap home directory. But that requires a semi-working launcher ;)
> 
> https://forum.snapcraft.io/t/the-homeishome-launcher-fix-snapped-apps-that-wrongly-referring-to-the-users-real-home-directory-instead-of-home/19763

Okay this is working. Version 8.2 built locally, installs and runs fine - latest launcher, no issues. If anyone wants to test in `--edge` and get back to me, we'll publish to `stable` ASAP.

**Comment by kz6fittycent** [comment]
`sudo snap refresh mc-installer --edge` if you would like to give it a run and report back. TIA!

**Comment by kz6fittycent** [comment]
I'm gonna go ahead and push to `stable` I am getting solid results out of `edge`.

**Comment by edmcdonagh** [comment]
Thanks @kz6fittycent - finally managed to test this this weekend - we had to delete/move the `~/snap/mc-installer` directory before it would launch, but now it works well. Thank you!

**Comment by Grimpen** [comment]
Thank you so much for your efforts!

**Comment by kz6fittycent** [comment]
`personal-files` plug has been approved. Pushing to `testing` branch now -will build locally.

**Comment by kz6fittycent** [comment]
pushed to `edge` and ready for testing. It's working well on my machine at home.
